# syntax=docker/dockerfile:1
FROM continuumio/miniconda3:4.10.3 AS build
LABEL Description="openeye-toolkits:2021.2.0 build"

ENV TZ=America/Chicago \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /app
SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get -y --no-install-recommends install \
    vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install conda packages
RUN conda install -y -q -c openeye openeye-toolkits=2021.2.0 && \
    conda install -y -q numpy=1.20.3 scipy=1.7.1


#FROM continuumio/miniconda3:4.10.3 AS runtime
#LABEL Description="openeye-toolkits:2021.2.0 runtime"
#
##COPY --from=build /app/xx /app/xx
#
#WORKDIR /mnt
