# syntax=docker/dockerfile:1
FROM debian:12.0-slim AS build
LABEL Description="openeye-toolkits:2021.2.0 build"

ENV TZ=America/Chicago \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /app
SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get -y --no-install-recommends install \
    vim faketime && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./packages/2021.2.0/Miniconda3-py39_4.12.0-Linux-x86_64.sh /app/
RUN cd /app/ && /bin/bash ./Miniconda3-py39_4.12.0-Linux-x86_64.sh -b -p /app/miniconda
ENV PATH=/app/miniconda/bin:${PATH}

RUN conda install -y -q -c openeye openeye-toolkits=2021.2.0 && \
    conda install -y -q numpy=1.20.3 scipy=1.7.1


FROM debian:12.0-slim AS runtime
LABEL Description="openeye-toolkits:2021.2.0 runtime"

ENV TZ=America/Chicago \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -y --no-install-recommends install \
    vim faketime procps && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /app/miniconda /app/miniconda
ENV PATH=/app/miniconda/bin:${PATH}
ENV OE_LICENSE=/app/oe_license.txt

WORKDIR /mnt
